In [1]:
import pandas as pd
from functools import reduce
from pathlib import Path
import os

In [20]:
gene_name="cNOR"
tax_level="family"

In [21]:
tax_list = [ f for f in os.listdir('.') if f.endswith(tax_level)]

In [22]:
tax_df_list = []
for file in tax_list:
    clean_df = "df_"+file
    clean_df = pd.read_csv(file, sep="\t")
    tax_df_list.append(clean_df)

In [23]:
all_combined = reduce(lambda  left,right: pd.merge(left,right,on=tax_level,how='outer'), tax_df_list)

In [24]:
all_combined = all_combined.reindex(sorted(all_combined.columns), axis=1)
all_combined = all_combined[ [tax_level] + [ col for col in all_combined.columns if col != tax_level ] ]
all_combined

,family,count_5158_A_val_1,count_5158_A_val_2,count_5158_B_val_1,count_5158_B_val_2,count_5158_C_val_1,count_5158_C_val_2,count_5158_D_val_1,count_5158_D_val_2,count_5158_E_val_1,count_5158_E_val_2,count_5158_F_val_1,count_5158_F_val_2,count_5158_G_val_1,count_5158_G_val_2,count_5158_H_val_1,count_5158_H_val_2
0,NaN,3.0,2.0,4.0,1.0,3.0,1.0,NaN,NaN,1.0,3.0,2.0,2.0,5.0,4.0,NaN,2.0
1,Akkermansiaceae,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Arcobacteraceae,1.0,5.0,1.0,1.0,NaN,NaN,NaN,NaN,21.0,16.0,309.0,310.0,154.0,160.0,14.0,16.0
3,Bdellovibrionaceae,3.0,5.0,2.0,5.0,1.0,1.0,7.0,NaN,2.0,1.0,NaN,2.0,NaN,1.0,4.0,3.0
4,CAIWAD01,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,1.0,1.0,NaN,NaN,NaN,NaN,NaN,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
157,CAIKAF01,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
158,Geobacteraceae,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
159,UBA2394,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
160,UBA6191,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
161,UBA9968,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [25]:
pd.DataFrame.to_csv(all_combined, gene_name+'___'+tax_level+'___Black_sea_MG.tsv', sep='\t', index=False)